image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - yarn
    - yarn build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour
  only:
    - main

deploy-to-s3:
  stage: deploy
  image: python:latest
  script:
    - pip install awscli
    - aws s3 sync dist/ s3://$S3_BUCKET_NAME --delete
    - aws s3 cp s3://$S3_BUCKET_NAME s3://$S3_BUCKET_NAME --recursive --acl public-read
  dependencies:
    - build
  only:
    - main
