image: node:latest

stages:
  - build
  - deploy

cache:
  key: yarn-cache
  paths:
    - .yarn/cache
    - node_modules/

build:
  stage: build
  tags:
    - frontend-runner
  before_script:
    - echo "VITE_CHAT_BASE_URL=${VITE_CHAT_BASE_URL}" >> .env
    - echo "VITE_AUTH_BASE_URL=${VITE_AUTH_BASE_URL}" >> .env
  script:
    - yarn install --frozen-lockfile
    - yarn build --minify=esbuild
  artifacts:
    paths:
      - dist/
    expire_in: 30m
  only:
    - main

deploy-to-s3:
  stage: deploy
  tags:
    - frontend-runner
  image: amazon/aws-cli
  script:
    - aws s3 sync dist/ s3://$S3_BUCKET_NAME --delete
  dependencies:
    - build
  only:
    - main

purge:
  image: amazon/aws-cli
  stage: deploy
  tags:
    - frontend-runner
  script:
    - aws cloudfront create-invalidation --distribution-id $PROD_CLOUDFRONT_DIST --paths "/*"
  only:
    - main