image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/
    - yarn.lock
  key:
    files:
      - yarn.lock

build:
  stage: build
  tags:
    - frontend-runner
  script:
    - echo "VITE_CHAT_BASE_URL=${VITE_CHAT_BASE_URL_DEV}" >> .env
    - echo "VITE_AUTH_BASE_URL=${VITE_AUTH_BASE_URL_DEV}" >> .env
    - yarn install --frozen-lockfile
    - yarn build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour
  only:
    - dev

deploy-to-s3:
  stage: deploy
  tags:
    - frontend-runner
  image: python:3.9-alpine
  before_script:
    - pip install awscli
  script:
    - aws s3 sync dist/ s3://$S3_BUCKET_NAME --delete
  dependencies:
    - build
  only:
    - dev
