image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/
    - yarn.lock
  key:
    files:
      - yarn.lock

build:
  stage: build
  tags:
    - frontend-runner
  script:
    - echo "VITE_CHAT_BASE_URL=${CHAT_BASE_URL_PROD}" >> .env
    - echo "VITE_AUTH_BASE_URL=${AUTH_BASE_URL_PROD}" >> .env
    - yarn install --frozen-lockfile
    - yarn build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour
  only:
    - main

deploy-to-s3:
  stage: deploy
  needs: [build]
  tags:
    - frontend-runner
  image: python:3.9-alpine
  before_script:
    - pip install awscli
  script:
    - aws s3 sync dist/ s3://$S3_BUCKET_NAME --delete
  dependencies:
    - build
  only:
    - main

purge:
  stage: deploy
  needs: [deploy-to-s3]
  image: python:3.9-alpine
  before_script:
    - pip install awscli
  tags:
    - frontend-runner
  script:
    - aws cloudfront create-invalidation --distribution-id $PROD_CLOUDFRONT_DIST --paths "/*"
  only:
    - main
