image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  tags:
    - frontend-runner
  script:
    # 환경 변수 설정 전에 값 확인
    - echo "환경 변수 확인:"
    - echo "VITE_CHAT_BASE_URL_DEV = ${VITE_CHAT_BASE_URL_DEV}"
    - echo "VITE_AUTH_BASE_URL_DEV = ${VITE_AUTH_BASE_URL_DEV}"
    
    # 환경 변수 설정
    - echo "VITE_CHAT_BASE_URL=${VITE_CHAT_BASE_URL_DEV}" >> .env
    - echo "VITE_AUTH_BASE_URL=${VITE_AUTH_BASE_URL_DEV}" >> .env
    
    # .env 파일 내용 확인
    - echo "생성된 .env 파일 내용:"
    - cat .env

    - yarn build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour
  only:
    - dev

deploy-to-s3:
  stage: deploy
  tags:
    - frontend-runner
  image: python:3.9-alpine
  before_script:
    - pip install awscli
  script:
    - aws s3 sync dist/ s3://$S3_BUCKET_NAME_DEV --delete
  dependencies:
    - build
  only:
    - dev
