version: '3.8'
services:
  frontend:
    image: bestlalala/autobot-app:1.0.1
    ports:
      - "80:80"
    environment:
      - VITE_AUTH_BASE_URL=http://your-custom-url:8080
      - VITE_CHAT_BASE_URL=http://your-custom-url:8080